POST http://localhost:3003/api/blogs/
content-type: application/json

 {
      "title": "Type wars",
      "author": "Robert C. Martin",
      "url":"http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html"


}